apiVersion: v1
kind: ConfigMap
metadata:
  name: seirv-config
data:
  API_V1_PREFIX: "/api/v1"
  DEBUG: "False"
  ALGORITHM: "HS256"
  PYTHONPATH: "/code"
  # Actualizar con la IP de Minikube: agregar http://<minikube-ip>:30300
  CORS_ORIGINS: "http://localhost:3000,http://localhost:30300"
