apiVersion: v1
kind: Secret
metadata:
  name: seirv-secrets
type: Opaque
data:
  # seirv_user
  POSTGRES_USER: c2VpcnZfdXNlcg==
  # seirv_password
  POSTGRES_PASSWORD: c2VpcnZfcGFzc3dvcmQ=
  # seirv_db
  POSTGRES_DB: c2VpcnZfZGI=
  # postgresql://seirv_user:seirv_password@postgres-service:5432/seirv_db
  DATABASE_URL: cG9zdGdyZXNxbDovL3NlaXJ2X3VzZXI6c2VpcnZfcGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL3NlaXJ2X2Ri
  # super-secret-key-for-seirv-demo-32chars
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1mb3Itc2VpcnYtZGVtby0zMmNoYXJz
  # 30
  ACCESS_TOKEN_EXPIRE_MINUTES: MzA=
