"""add license_plate to vehicles

Revision ID: 75d127aeea6e
Revises: 
Create Date: 2025-11-13 17:52:52.765264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d127aeea6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Verificar si la columna ya existe
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('vehicles')]
    
    if 'license_plate' not in columns:
        # Paso 1: Agregar columna como nullable primero
        op.add_column('vehicles', sa.Column('license_plate', sa.String(length=8), nullable=True))
        
        # Paso 2: Asignar valores temporales a registros existentes (si los hay)
        # Genera placas únicas temporales: XXX-0001, XXX-0002, etc.
        op.execute("""
            UPDATE vehicles 
            SET license_plate = 'XXX-' || LPAD(id::text, 4, '0')
            WHERE license_plate IS NULL
        """)
        
        # Paso 3: Ahora hacer la columna NOT NULL
        op.alter_column('vehicles', 'license_plate', nullable=False)
    
    # Verificar si el índice ya existe
    indexes = [idx['name'] for idx in inspector.get_indexes('vehicles')]
    if 'ix_vehicles_license_plate' not in indexes:
        op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=False)
    
    # Verificar si el constraint ya existe
    constraints = [c['name'] for c in inspector.get_unique_constraints('vehicles')]
    if 'unique_license_plate' not in constraints:
        op.create_unique_constraint('unique_license_plate', 'vehicles', ['license_plate'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_license_plate', 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_column('vehicles', 'license_plate')
    # ### end Alembic commands ###
