"""add license_plate to vehicles

Revision ID: 75d127aeea6e
Revises: 
Create Date: 2025-11-13 17:52:52.765264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d127aeea6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Paso 1: Agregar columna como nullable primero
    op.add_column('vehicles', sa.Column('license_plate', sa.String(length=8), nullable=True))
    
    # Paso 2: Asignar valores temporales a registros existentes (si los hay)
    # Genera placas únicas temporales: XXX-0001, XXX-0002, etc.
    op.execute("""
        UPDATE vehicles 
        SET license_plate = 'XXX-' || LPAD(id::text, 4, '0')
        WHERE license_plate IS NULL
    """)
    
    # Paso 3: Ahora hacer la columna NOT NULL
    op.alter_column('vehicles', 'license_plate', nullable=False)
    
    # Paso 4: Crear índice y constraint
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=False)
    op.create_unique_constraint('unique_license_plate', 'vehicles', ['license_plate'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_license_plate', 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_column('vehicles', 'license_plate')
    # ### end Alembic commands ###
